//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVarzea.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepVarzeaEntities : DbContext
    {
        public RepVarzeaEntities()
            : base("name=RepVarzeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GASTO> GASTO { get; set; }
        public virtual DbSet<GASTO_MORADOR> GASTO_MORADOR { get; set; }
        public virtual DbSet<MORADOR> MORADOR { get; set; }
    }
}
