//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVarzea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GASTO()
        {
            this.GASTO_MORADOR = new HashSet<GASTO_MORADOR>();
        }
    
        public int id_gasto { get; set; }
        public int id_morador { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual MORADOR MORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTO_MORADOR> GASTO_MORADOR { get; set; }
    }
}
