//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVarzea.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GASTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GASTO()
        {
            this.GASTO_MORADOR = new HashSet<GASTO_MORADOR>();
        }
    
        [Key]
        public int id_gasto { get; set; }

        [Required(ErrorMessage = "Favor fazer o login para continuar.")]
        public int id_morador { get; set; }

        [Required(ErrorMessage = "Favor informar a descrição.")]
        public string descricao { get; set; }

        [Required(ErrorMessage = "Favor informar a data.")]
        [DataType(DataType.DateTime)]
        public DateTime data { get; set; }
        
        [Required(ErrorMessage = "Favor informar o valor gasto.")]
        [RegularExpression(@"^[a-zA-Z0-9]*$",ErrorMessage = "Insira um valor válido.")]
        public float valor { get; set; }
    
        public virtual MORADOR MORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTO_MORADOR> GASTO_MORADOR { get; set; }
    }
}
