//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteVarzea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MORADOR()
        {
            this.GASTO_MORADOR = new HashSet<GASTO_MORADOR>();
        }
    
        public int id_morador { get; set; }
        public string nome { get; set; }
        public Nullable<decimal> ano { get; set; }
        public string email { get; set; }
        public Nullable<decimal> ativo { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    
        public virtual GASTO GASTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GASTO_MORADOR> GASTO_MORADOR { get; set; }
    }
}
